service: c7p-translate
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}
  dotenv:
    path: ../.env
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:DetectDominantLanguage
        - translate:TranslateText
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource: "*"
resources:
  Resources:
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:CHAPTER7_PIPELINE_SENTIMENT_STREAM}
        ShardCount: ${env:CHAPTER7_PIPELINE_SHARD_COUNT}
functions:
  translate:
    handler: handler.translate
    events:
      - stream:
          type: kinesis
          arn: ${env:CHAPTER7_PIPELINE_TRANSLATE_STREAM_ARN}
          batchSize: 100
          startingPosition: LATEST
          enabled: true
          async: true

